### ISSUE TITLE
Allow setting a unique ID

### ISSUE THREAD

**Issue by schmidtfx** [neuhausf/swiss-public-transport-mod#4]
The integration does not allow setting a unique ID for the sensor.

**Comment by neuhausf** [comment]
@schmidtfx you can set now the unique_id in yaml:
![image](https://github.com/user-attachments/assets/0d6798c3-e99a-4cae-9bde-37f76aaf8be0)
any value you like 😉

**Comment by schmidtfx** [comment]
You are amazing.
